function addMeshBlock(varargin)

grid = t6.TrogdorSimulation.instance().CurrentGrid;

obj = struct;
obj.type = 'Mesh';

X.YeeBounds = [0 0 0 0 0 0];
X.Permittivity = '';
X.Permeability = '';
X = parseargs(X, varargin{:});

if ~t6.validateRect(X.YeeBounds)
    error('Invalid rectangle.');
end

if ~isempty(X.Permittivity)
    obj.permittivity = X.Permittivity;
end

if ~isempty(X.Permeability)
    obj.permeability = X.Permeability;
end

b = X.YeeBounds;

obj.vertices = [...
    b([1 2 3]); ...
    b([4 2 3]); ...
    b([1 5 3]); ...
    b([4 5 3]); ...
    b([1 2 6]); ...
    b([4 2 6]); ...
    b([1 5 6]); ...
    b([4 5 6]); ...
];

obj.vertexFreeDirections = zeros(size(obj.vertices));

obj.faces = [...
    [0 4 6 2]; ...
    [1 3 7 5]; ...
    [0 1 5 4]; ...
    [3 2 6 7]; ...
    [0 2 3 1]; ...
    [4 5 7 6]; ...
];

grid.Assembly = {grid.Assembly{:}, obj};